# Cloudflare Pages 部署配置
# 这个文件会被 Cloudflare Pages 自动识别

[build]
  # 构建命令
  command = "npm run build"

  # 构建输出目录 (Next exported static site)
  publish = "out"
  # 指定 Pages 导出目录，供 wrangler 使用
  pages_build_output_dir = "out"

  # Node.js 版本
  [build.environment]
    NODE_VERSION = "18"
    NEXT_TELEMETRY_DISABLED = "1"

# 生产环境变量 - 所有变量都通过 wrangler pages secret 设置
[env.production]
  NODE_ENV = "production"
  # NEXT_PUBLIC_UPLOAD_API - Set via: npx wrangler pages secret put NEXT_PUBLIC_UPLOAD_API
  # NEXT_PUBLIC_ADMIN_API - Set via: npx wrangler pages secret put NEXT_PUBLIC_ADMIN_API
  # NEXT_PUBLIC_HISTORY_API - Set via: npx wrangler pages secret put NEXT_PUBLIC_HISTORY_API
  # NEXT_PUBLIC_CDN_BASE - Set via: npx wrangler pages secret put NEXT_PUBLIC_CDN_BASE

# 预览环境变量 - 开发环境使用
[env.preview]
  NODE_ENV = "development"
  # NEXT_PUBLIC_UPLOAD_API - Set via: npx wrangler pages secret put NEXT_PUBLIC_UPLOAD_API
  # NEXT_PUBLIC_ADMIN_API - Set via: npx wrangler pages secret put NEXT_PUBLIC_ADMIN_API
  # NEXT_PUBLIC_HISTORY_API - Set via: npx wrangler pages secret put NEXT_PUBLIC_HISTORY_API
  # NEXT_PUBLIC_CDN_BASE - Set via: npx wrangler pages secret put NEXT_PUBLIC_CDN_BASE

# 重定向规则
[[redirects]]
  from = "/api/*"
  to = "https://uploader-worker-prod.haoweiw370.workers.dev/:splat"
  status = 200
  force = true

# Headers 配置 - 性能和安全优化
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# 静态资源缓存
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
