# Cloudflare Pages 部署配置
# 这个文件会被 Cloudflare Pages 自动识别

[build]
  # 构建命令
  command = "npm run build"
  
  # 构建输出目录
  publish = ".next"
  
  # Node.js 版本
  [build.environment]
    NODE_VERSION = "18"
    NEXT_TELEMETRY_DISABLED = "1"

# 生产环境变量
[env.production]
  NODE_ENV = "production"

# 预览环境变量  
[env.preview]
  NODE_ENV = "development"

# 重定向规则
[[redirects]]
  from = "/api/*"
  to = "https://your-worker.workers.dev/:splat"
  status = 200
  force = true

# Headers 配置 - 性能和安全优化
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# 静态资源缓存
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
