name = "cdn-worker"
main = "src/index.ts"
compatibility_date = "2025-10-20"

# Replace with your account ID (get from: wrangler whoami)
account_id = "fc590bfe34fc6df2312c469a5db04aa2"

# R2 Bucket binding
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "lambdaimagebucket"

# Environment variables
[vars]
ALLOWED_ORIGINS = "*"  # CORS: comma-separated origins or "*"
CACHE_MAX_AGE = "31536000"  # 1 year cache for images

# Production environment
[env.production]
name = "cdn-worker-prod"

# Bind to custom domain for CDN
routes = [
  { pattern = "pic.lambdax.me/*", zone_name = "lambdax.me" }
]

[env.production.vars]
ALLOWED_ORIGINS = "*"
CACHE_MAX_AGE = "31536000"

[[env.production.r2_buckets]]
binding = "IMAGES"
bucket_name = "lambdaimagebucket"
