name = "agent-database"
main = "agent-database-worker.js"
compatibility_date = "2024-01-01"

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "agent-database"
database_id = "your_database_id_here"

# 环境变量
[vars]
ENVIRONMENT = "production"
