name = "agent-proxy"
main = "agent-proxy.ts"
compatibility_date = "2024-10-27"

# 全局变量配置
[vars]
# AGENT_API_KEY 应该通过 wrangler secret 设置
# 运行: wrangler secret put AGENT_API_KEY

# 生产环境配置
[env.production]
name = "agent-proxy"

# 测试环境配置
[env.staging]
name = "agent-proxy-staging"

# 开发环境配置
[env.development]
name = "agent-proxy-dev"
