name = "r2-browser-worker-v2-prod"
main = "r2-browser.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "next-lambda-image-r2"

[[d1_databases]]
binding = "DB"
database_name = "v2-pico-pics-db1"
database_id = "90ca5dd2-fc00-475b-99ac-99810d559356"

[vars]
ALLOWED_ORIGINS = "*"
# ADMIN_TOKEN 应该通过 wrangler secret 设置
# 运行: wrangler secret put ADMIN_TOKEN
