name = "uploader-worker-prod"
main = "src/index.ts"
compatibility_date = "2025-10-20"

# Account ID will be set via environment variable or wrangler secret
# account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

# R2 Bucket binding - bucket_name will be set via environment variable
# [[r2_buckets]]
# binding = "IMAGES"
# bucket_name = "YOUR_R2_BUCKET_NAME"

# KV namespace for caching GitHub user info - id will be set via environment variable
# [[kv_namespaces]]
# binding = "USER_CACHE"
# id = "YOUR_KV_NAMESPACE_ID"

# Cloudflare AI binding
[ai]
binding = "AI"

# D1 Database binding - database_id will be set via environment variable
# [[d1_databases]]
# binding = "DB"
# database_name = "YOUR_D1_DATABASE_NAME"
# database_id = "YOUR_D1_DATABASE_ID"

# Environment variables - will be set via wrangler secret or environment variables
[vars]
# R2_PUBLIC_BASE - Set via: npx wrangler secret put R2_PUBLIC_BASE --env production
# MAX_UPLOAD_SIZE - Set via: npx wrangler secret put MAX_UPLOAD_SIZE --env production
# ALLOWED_ORIGINS - Set via: npx wrangler secret put ALLOWED_ORIGINS --env production
# DAILY_QUOTA_BYTES - Set via: npx wrangler secret put DAILY_QUOTA_BYTES --env production
ABUSE_DETECTION_ENABLED = "true"  # Enable abuse detection and IP banning
TURNSTILE_ENABLED = "false"  # Disable Cloudflare Turnstile verification
AUTH_ENABLED = "true"  # Enable GitHub OAuth authentication
CONTENT_MODERATION_ENABLED = "true"  # Enable AI-powered content moderation
# ADMIN_USERS - Set via: npx wrangler secret put ADMIN_USERS --env production
# ADMIN_TOKEN - Set via: npx wrangler secret put ADMIN_TOKEN --env production
# TELEGRAM_BOT_TOKEN - Set via: npx wrangler secret put TELEGRAM_BOT_TOKEN --env production
# TELEGRAM_CHAT_ID - Set via: npx wrangler secret put TELEGRAM_CHAT_ID --env production
# TURNSTILE_SECRET_KEY - Set via: npx wrangler secret put TURNSTILE_SECRET_KEY --env production

# Durable Object for daily quota tracking
[[durable_objects.bindings]]
name = "UPLOAD_QUOTA"
class_name = "UploadQuota"
script_name = "uploader-worker-prod"

# Durable Object for IP blacklist and abuse detection
[[durable_objects.bindings]]
name = "IP_BLACKLIST"
class_name = "IPBlacklist"
script_name = "uploader-worker-prod"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["UploadQuota"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["IPBlacklist"]

# Production environment
[env.production]
name = "uploader-worker-prod"

# Account ID - Set via: npx wrangler secret put CLOUDFLARE_ACCOUNT_ID --env production
# account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

# R2 Bucket binding - bucket_name will be set via environment variable
# [[env.production.r2_buckets]]
# binding = "IMAGES"
# bucket_name = "YOUR_R2_BUCKET_NAME"

# KV namespace - id will be set via environment variable
# [[env.production.kv_namespaces]]
# binding = "USER_CACHE"
# id = "YOUR_KV_NAMESPACE_ID"

# Cloudflare AI binding
[env.production.ai]
binding = "AI"

# D1 Database binding - database_id will be set via environment variable
# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "YOUR_D1_DATABASE_NAME"
# database_id = "YOUR_D1_DATABASE_ID"

# Environment variables - will be set via wrangler secret
[env.production.vars]
ABUSE_DETECTION_ENABLED = "true"
TURNSTILE_ENABLED = "false"
AUTH_ENABLED = "true"
CONTENT_MODERATION_ENABLED = "true"
DAILY_UPLOAD_LIMIT_PER_IP = "20"
# All other variables will be set via wrangler secret commands

# Durable Objects
[[env.production.durable_objects.bindings]]
name = "UPLOAD_QUOTA"
class_name = "UploadQuota"
script_name = "uploader-worker-prod"

[[env.production.durable_objects.bindings]]
name = "IP_BLACKLIST"
class_name = "IPBlacklist"
script_name = "uploader-worker-prod"

[[env.production.migrations]]
tag = "v1"
new_sqlite_classes = ["UploadQuota"]

[[env.production.migrations]]
tag = "v2"
new_sqlite_classes = ["IPBlacklist"]
